export const GET_CATEGORY_LOAD="GET_CATEGORY_LOAD";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL="GET_CATEGORY_FAIL";
export const GET_CATEGORY="GET_CATEGORY";
export const POST_CATEGORY="POST_CATEGORY";
export const POST_CATEGORY_FAIL="POST_CATEGORY_FAIL";
export const DELETE_CATEGORY="DELETE_CATEGORY";