export const GET_RESERVATION_LOAD="GET_RESERVATION_LOAD";
export const GET_RESERVATION_SUCCESS="GET_RESERVATION_SUCCESS";
export const GET_RESERVATION_FAIL="GET_RESERVATION_FAIL";
export const GET_RESERVATION="GET_RESERVATION";
export const POST_RESERVATION="POST_RESERVATION";
export const POST_RESERVATION_FAIL="POST_RESERVATION_FAIL";
export const DELETE_RESERVATION="DELETE_RESERVATION";